image: node:16

stages:
  - setup
  - test
  - release

cache:
  paths:
    - node_modules/

setup:
  stage: setup
  script:
    - npm install

test:
  stage: test
  script:
    - npm run test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
    - coverage/
    expire_in: 7 days

npm-publish:
  stage: release
  script:
    - npx semantic-release
  only:
    - master